name: azlistview
version: 2.0.0+patch
publish_to: none
description: Local patched azlistview with Flutter 3 fixes

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
